meta:
  image: pojntfx/unnecessary-ly-backend:latest
  dev: false
  debugPort: 8080
  debugNodePort: 38080
  target: "{{ .DIBS_TARGET }}"
  platform: "{{ .TARGETPLATFORM }}"
  debug: "{{ .DIBS_DEBUG }}"
  lport: 1999
  dbhost: unnecessary-ly-backend-postgresql
  dbport: 5432
  smtphost: mail.example.com
  smtpport: 587
  smtpusr: system@example.com
  smtppass: supersecretpass
  smtpemail: system@example.com
  bushost: unnecessary-ly-backend-nats-client
  busport: 4222

resources:
  memory: "1024Mi"
  cpu: "1024m"
  maxReplicas: 10

ingress:
  nodePort: 31999
  domain: unnecessary-ly-backend.example.com
  path: /

postgresql:
  postgresqlUsername: exampleuser1
  postgresqlPassword: supersecretpass1
  postgresqlDatabase: exampledb

nats:
  auth:
    user: exampleuser2
    password: supersecretpass2
