-- apply changes
create table room (
  id                            integer generated by default as identity not null,
  title                         varchar(255),
  constraint pk_room primary key (id)
);

