-- apply changes
create table community (
  id                            bigint generated by default as identity not null,
  display_name                  varchar(255),
  owner_id                      bigint not null,
  constraint pk_community primary key (id)
);

create table users (
  id                            bigint generated by default as identity not null,
  display_name                  varchar(255),
  email                         varchar(255),
  password                      varchar(255),
  user_signup_request_id        bigint,
  user_password_reset_request_id bigint,
  constraint uq_users_email unique (email),
  constraint uq_users_user_signup_request_id unique (user_signup_request_id),
  constraint uq_users_user_password_reset_request_id unique (user_password_reset_request_id),
  constraint pk_users primary key (id)
);

create table user_password_reset_request (
  id                            bigint generated by default as identity not null,
  token                         varchar(255),
  confirmed                     boolean default false not null,
  constraint pk_user_password_reset_request primary key (id)
);

create table user_sign_up_request (
  id                            bigint generated by default as identity not null,
  token                         varchar(255),
  confirmed                     boolean default false not null,
  constraint pk_user_sign_up_request primary key (id)
);

create index ix_community_owner_id on community (owner_id);
alter table community add constraint fk_community_owner_id foreign key (owner_id) references users (id) on delete restrict on update restrict;

alter table users add constraint fk_users_user_signup_request_id foreign key (user_signup_request_id) references user_sign_up_request (id) on delete restrict on update restrict;

alter table users add constraint fk_users_user_password_reset_request_id foreign key (user_password_reset_request_id) references user_password_reset_request (id) on delete restrict on update restrict;

