-- apply changes
create table channel (
  id                            bigint generated by default as identity not null,
  display_name                  varchar(255),
  community_id                  bigint not null,
  constraint pk_channel primary key (id)
);

create index ix_channel_community_id on channel (community_id);
alter table channel add constraint fk_channel_community_id foreign key (community_id) references community (id) on delete restrict on update restrict;

