-- apply changes
create table user_sign_up_request (
  id                            bigint generated by default as identity not null,
  token                         varchar(255),
  confirmed                     boolean default false not null,
  constraint pk_user_sign_up_request primary key (id)
);

alter table users add column user_signup_request_id bigint;

alter table users add constraint fk_users_user_signup_request_id foreign key (user_signup_request_id) references user_sign_up_request (id) on delete restrict on update restrict;

