-- apply changes
create table chat (
  id                            bigint generated by default as identity not null,
  message                       varchar(255),
  channel_id                    bigint not null,
  user_id                       bigint not null,
  constraint pk_chat primary key (id)
);

create index ix_chat_channel_id on chat (channel_id);
alter table chat add constraint fk_chat_channel_id foreign key (channel_id) references channel (id) on delete restrict on update restrict;

create index ix_chat_user_id on chat (user_id);
alter table chat add constraint fk_chat_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

