ebean:
  dbSchema: unnecessary_ly_server
  migration:
    run: true

datasource:
  db:
    username: ${dbusr}
    password: ${dbpass}
    url: jdbc:postgresql://${dbhost}:${dbport}/${dbname}
    driver: org.postgresql.Driver
