
apiVersion: v1
kind: ConfigMap
metadata:
  name: unnecessary-ly-backend{{ if .Values.meta.dev }}-dev{{ end }}
data:
  DIBS_TARGET: "{{ .Values.meta.target }}"
  TARGETPLATFORM: "{{ .Values.meta.platform }}"
  {{ if and .Values.meta.dev .Values.meta.debug }}
  DIBS_DEBUG: "true"
  {{end}}
  ULY_LPORT: "{{ .Values.meta.lport }}"
  ULY_DBUSR: "{{ .Values.postgresql.postgresqlUsername }}"
  ULY_DBPASS: "{{ .Values.postgresql.postgresqlPassword }}"
  ULY_DBHOST: "{{ .Values.meta.dbhost }}"
  ULY_DBPORT: "{{ .Values.meta.dbport }}"
  ULY_DBNAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  ULY_SMTPHOST: "{{ .Values.meta.smtphost }}"
  ULY_SMTPPORT: "{{ .Values.meta.smtpport }}"
  ULY_SMTPUSR: "{{ .Values.meta.smtpusr }}"
  ULY_SMTPPASS: "{{ .Values.meta.smtppass }}"
  ULY_SMTPEMAIL: "{{ .Values.meta.smtpemail }}"
  ULY_BUSHOST: "{{ .Values.meta.bushost }}"
  ULY_BUSPORT: "{{ .Values.meta.busport }}"
  ULY_BUSUSR: "{{ .Values.nats.auth.user }}"
  ULY_BUSPASS: "{{ .Values.nats.auth.password }}"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unnecessary-ly-backend{{ if .Values.meta.dev }}-dev{{ end }}
spec:
  selector:
    matchLabels:
      app: unnecessary-ly-backend{{ if .Values.meta.dev }}-dev{{ end }}
  template:
    metadata:
      labels:
        app: unnecessary-ly-backend{{ if .Values.meta.dev }}-dev{{ end }}
    spec:
      containers:
        - name: unnecessary-ly-backend{{ if .Values.meta.dev }}-dev{{ end }}
          image: {{ .Values.meta.image }}
          envFrom:
            - configMapRef:
                name: unnecessary-ly-backend{{ if .Values.meta.dev }}-dev{{ end }}
          {{ if not .Values.meta.dev }}
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
              cpu: {{ .Values.resources.cpu }}
          {{ end }}
          ports:
            - containerPort: 1999
            {{ if and .Values.meta.dev .Values.meta.debug }}
            - containerPort: {{ .Values.meta.debugPort }}
            {{end}}
  {{ if .Values.meta.dev }}

---
apiVersion: v1
kind: Service
metadata:
  name: unnecessary-ly-backend-dev
spec:
  selector:
    app: unnecessary-ly-backend-dev
  type: NodePort
  ports:
    - name: grpc
      port: 1999
      targetPort: 1999
      nodePort: {{ .Values.ingress.nodePort }}
    - name: debug
      port: {{ .Values.meta.debugNodePort }}
      targetPort: {{ .Values.meta.debugPort }}
      nodePort: {{ .Values.meta.debugNodePort }}
  {{ else }}

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: unnecessary-ly-backend
spec:
  maxReplicas: {{ .Values.resources.maxReplicas }}
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unnecessary-ly-backend
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60

---
apiVersion: v1
kind: Service
metadata:
  name: unnecessary-ly-backend
spec:
  selector:
    app: unnecessary-ly-backend
  ports:
    - name: grpc
      port: 1999
      targetPort: 1999

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: unnecessary-ly-backend
  annotations:
    ingress.kubernetes.io/protocol: h2c
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: unnecessary-ly-backend
              servicePort: grpc
  {{ end }}